### PR TITLE
Images by tag

### LINKED ISSUE #9: Images by Tag
#### As a user I want to view all images associated with a tag.

Acceptance criteria:
- [ ] When I click on a tag, I see a filtered list of only the images that have
  the tag I clicked on.
- [ ] The tag name (not its ID) is used to perform the filtering.

Discussion topics:
- [ ] Where should we implement this functionality?
- [ ] What happens if a user tries to manually filter by a nonexistent tag?

Dependencies:
- Image Tags

### PR DESCRIPTION
**Pull request by tlconnor**
Closes #9

### CODE REVIEW

**Comment by bboe** [comment]
I like that you chose to implement this on the client-side. Will you, however, provide the API such that the image list can be filtered by a given tag and utilize that resource for displaying images by tag?

The practical use-case here is that at some point our app will have too many images to fetch all in a single request. While we don't actually do pagination in Ropes, it is something we had wanted to introduce.

**Comment by tlconnor** [comment]
@bboe I have an issue with adding the filtered API unless the original request was already filtered in some way (e.g pagination).

If I were to make the suggested change the app would retrieve ALL data on the original navigation to /images and then re-retrieve a subset of that data when filtering.

The only difference for the end user will be a noticeable delay when filtering as opposed to the current experience which is instantaneous.

**Comment by tlconnor** [comment]
I've updated the API to allow the results to be filtered, but as I said in the previous comment there is no point hooking it up to the frontend.

**Comment by bboe** [comment]
Closing this to remove it from my list of mentioned pull requests.

**Pull request closed without merging**
